# Re-invitation to Julia

Let's blitz review the fundamentals of Julia. This is suitable as a very quick introduction for experienced programmers, or as a pre-review for the next step for people with some Julia knowledge.

For a more leisurely discussion, see my *Invitation to Julia* tutorial from JuliaCon 2015: https://www.youtube.com/watch?v=gQ1y5NUD_RI

### Financial support

Financial support is acknowledged from DGAPA-UNAM (Mexico) PAPIME grant PE-107114, DGAPA-UNAM PAPIIT grant IN-117214, and from a CONACYT-Mexico sabbatical fellowship. The author thanks Alan Edelman and the Julia group at MIT for hospitality during his sabbatical visit.

## Variables:

In [1]:
a = 2
a, typeof(a)

(2,Int64)

In [2]:
b = 3.5
b, typeof(b)

(3.5,Float64)

In [3]:
c = a + b

5.5

What does this do?

In [4]:
@which a + b

+(x::Number, y::Number) at promotion.jl:167

What is `+` actually?

In [5]:
+

+ (generic function with 171 methods)

In [6]:
methods(+)

# 171 methods for generic function "+":
+(x::Bool) at bool.jl:33
+(x::Bool, y::Bool) at bool.jl:36
+(y::AbstractFloat, x::Bool) at bool.jl:46
+(x::Int64, y::Int64) at int.jl:8
+(x::Int8, y::Int8) at int.jl:16
+(x::UInt8, y::UInt8) at int.jl:16
+(x::Int16, y::Int16) at int.jl:16
+(x::UInt16, y::UInt16) at int.jl:16
+(x::Int32, y::Int32) at int.jl:16
+(x::UInt32, y::UInt32) at int.jl:16
+(x::UInt64, y::UInt64) at int.jl:16
+(x::Int128, y::Int128) at int.jl:16
+(x::UInt128, y::UInt128) at int.jl:16
+(x::Integer, y::Ptr{T}) at pointer.jl:77
+(x::Float32, y::Float32) at float.jl:207
+(x::Float64, y::Float64) at float.jl:208
+(z::Complex{T<:Real}, w::Complex{T<:Real}) at complex.jl:111
+(x::Bool, z::Complex{Bool}) at complex.jl:118
+(z::Complex{Bool}, x::Bool) at complex.jl:119
+(x::Bool, z::Complex{T<:Real}) at complex.jl:125
+(z::Complex{T<:Real}, x::Bool) at complex.jl:126
+(x::Real, z::Complex{Bool}) at complex.jl:132
+(z::Complex{Bool}, x::Real) at complex.jl:133
+(x::Real, z::Complex{T<:Real}) at complex.jl:144
+(z::Complex{T<:Real}, x::Real) at complex.jl:145
+(x::Rational{T<:Integer}, y::Rational{T<:Integer}) at rational.jl:179
+(x::Bool, A::AbstractArray{Bool,N}) at arraymath.jl:136
+(x::Integer, y::Char) at char.jl:43
+(a::Float16, b::Float16) at float16.jl:136
+(x::BigInt, y::BigInt) at gmp.jl:256
+(a::BigInt, b::BigInt, c::BigInt) at gmp.jl:279
+(a::BigInt, b::BigInt, c::BigInt, d::BigInt) at gmp.jl:285
+(a::BigInt, b::BigInt, c::BigInt, d::BigInt, e::BigInt) at gmp.jl:292
+(x::BigInt, c::Union{UInt16,UInt32,UInt64,UInt8}) at gmp.jl:304
+(c::Union{UInt16,UInt32,UInt64,UInt8}, x::BigInt) at gmp.jl:308
+(x::BigInt, c::Union{Int16,Int32,Int64,Int8}) at gmp.jl:320
+(c::Union{Int16,Int32,Int64,Int8}, x::BigInt) at gmp.jl:321
+(x::BigFloat, y::BigFloat) at mpfr.jl:208
+(x::BigFloat, c::Union{UInt16,UInt32,UInt64,UInt8}) at mpfr.jl:215
+(c::Union{UInt16,UInt32,UInt64,UInt8}, x::BigFloat) at mpfr.jl:219
+(x::BigFloat, c::Union{Int16,Int32,Int64,Int8}) at mpfr.jl:223
+(c::Union{Int16,Int32,Int64,Int8}, x::BigFloat) at mpfr.jl:227
+(x::BigFloat, c::Union{Float16,Float32,Float64}) at mpfr.jl:231
+(c::Union{Float16,Float32,Float64}, x::BigFloat) at mpfr.jl:235
+(x::BigFloat, c::BigInt) at mpfr.jl:239
+(c::BigInt, x::BigFloat) at mpfr.jl:243
+(a::BigFloat, b::BigFloat, c::BigFloat) at mpfr.jl:379
+(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat) at mpfr.jl:385
+(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat, e::BigFloat) at mpfr.jl:392
+(x::Irrational{sym}, y::Irrational{sym}) at irrationals.jl:72
+(x::Number) at operators.jl:73
+{T<:Number}(x::T<:Number, y::T<:Number) at promotion.jl:211
+{T<:AbstractFloat}(x::Bool, y::T<:AbstractFloat) at bool.jl:43
+(x::Number, y::Number) at promotion.jl:167
+(r1::OrdinalRange{T,S}, r2::OrdinalRange{T,S}) at operators.jl:330
+{T<:AbstractFloat}(r1::FloatRange{T<:AbstractFloat}, r2::FloatRange{T<:AbstractFloat}) at operators.jl:337
+{T<:AbstractFloat}(r1::LinSpace{T<:AbstractFloat}, r2::LinSpace{T<:AbstractFloat}) at operators.jl:356
+(r1::Union{FloatRange{T<:AbstractFloat},LinSpace{T<:AbstractFloat},OrdinalRange{T,S}}, r2::Union{FloatRange{T<:AbstractFloat},LinSpace{T<:AbstractFloat},OrdinalRange{T,S}}) at operators.jl:369
+(x::Ptr{T}, y::Integer) at pointer.jl:75
+{S,T}(A::Range{S}, B::Range{T}) at arraymath.jl:69
+{S,T}(A::Range{S}, B::AbstractArray{T,N}) at arraymath.jl:87
+(A::BitArray{N}, B::BitArray{N}) at bitarray.jl:859
+{T}(B::BitArray{2}, J::UniformScaling{T}) at linalg/uniformscaling.jl:28
+(A::Array{T,2}, B::Diagonal{T}) at linalg/special.jl:122
+(A::Array{T,2}, B::Bidiagonal{T}) at linalg/special.jl:122
+(A::Array{T,2}, B::Tridiagonal{T}) at linalg/special.jl:122
+(A::Array{T,2}, B::SymTridiagonal{T}) at linalg/special.jl:131
+(A::Array{T,2}, B::Base.LinAlg.AbstractTriangular{T,S<:AbstractArray{T,2}}) at linalg/special.jl:159
+(A::Array{T,N}, B::SparseMatrixCSC{Tv,Ti<:Integer}) at sparse/sparsematrix.jl:1019
+{P<:Union{Base.Dates.CompoundPeriod,Base.Dates.Period}}(x::Union{De

We see that Julia calls specialised versions, called **methods** of a function. `+` and all other "operators" are just functions with (possibly) many methods. The act of choosing which method to use based on the *types* of all the arguments passed into the function is called **multiple dispatch**, one of the fundamental features of Julia.

We can follow down the chain of what is going on by looking at the code, or preferably using the new debugger integration in the Juno IDE:  `@step 2 + 3.5`

## When is Julia fast?

One of Julia's strengths is its blinding speed, which is perhaps unique among high-level languages.
However, it is easy enough to write *slow* Julia code! The point is that making slow code fast often requires following only a few rules.

Suppose we define a function

In [7]:
f(x, y) = x * y

f (generic function with 1 method)

In [8]:
f(3, 4)

12

In [9]:
f(3.5, 4.5)

15.75

Julia allows us to see various stages in the compilation process:

In [10]:
@code_lowered f(3, 4)

1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:x,:y], Any[Any[Any[:x,:Any,0],Any[:y,:Any,0]],Any[],0,Any[]], :(begin  # In[7], line 1:
        return x * y
    end))))

In [11]:
@code_typed f(3, 4)

1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:x,:y], Any[Any[Any[:x,Int64,0],Any[:y,Int64,0]],Any[],Any[],Any[]], :(begin  # In[7], line 1:
        return (Base.box)(Int64,(Base.mul_int)(x::Int64,y::Int64))
    end::Int64))))

or better

In [12]:
@code_warntype f(3, 4)

Variables:
  x::Int64
  y::Int64

Body:
  begin  # In[7], line 1:
      return (Base.box)(Int64,(Base.mul_int)(x::Int64,y::Int64))
  end::Int64


In [13]:
@code_llvm f(3, 4)


define i64 @julia_f_22319(i64, i64) {
top:
  %2 = mul i64 %1, %0
  ret i64 %2
}


In [14]:
@code_llvm f(3.5, 4)


define double @julia_f_22324(double, i64) {
top:
  %2 = sitofp i64 %1 to double
  %3 = fmul double %2, %0
  ret double %3
}


In [15]:
@code_native f(3, 4)

	.section	__TEXT,__text,regular,pure_instructions
Filename: In[7]
Source line: 1
	pushq	%rbp
	movq	%rsp, %rbp
Source line: 1
	imulq	%rsi, %rdi
	movq	%rdi, %rax
	popq	%rbp
	ret


In [16]:
@code_native f(3.5, 4.5)

	.section	__TEXT,__text,regular,pure_instructions
Filename: In[7]
Source line: 1
	pushq	%rbp
	movq	%rsp, %rbp
Source line: 1
	mulsd	%xmm1, %xmm0
	popq	%rbp
	ret


In [17]:
@code_native f(3, 4.5)

	.section	__TEXT,__text,regular,pure_instructions
Filename: In[7]
Source line: 1
	pushq	%rbp
	movq	%rsp, %rbp
Source line: 1
	cvtsi2sdq	%rdi, %xmm1
	mulsd	%xmm0, %xmm1
	movaps	%xmm1, %xmm0
	popq	%rbp
	ret


We see that Julia **generates highly-efficient code that is specialised on input type**. This is naturally true only **if Julia is able to correctly infer the types of every **.

For example:

In [18]:
function g(x)
    a = 1   # a starts off life as an integer
    a += x  # it may change type here
    return a
end
    

g (generic function with 1 method)

In [19]:
@code_warntype g(3)

Variables:
  x::Int64
  a::Int64

Body:
  begin  # In[18], line 2:
      a = 1 # In[18], line 3:
      a = (Base.box)(Base.Int,(Base.add_int)(a::Int64,x::Int64)) # In[18], line 4:
      return a::Int64
  end::Int64


In [21]:
@code_warntype g(3)

Variables:
  x::Int64
  a::Int64

Body:
  begin  # In[18], line 2:
      a = 1 # In[18], line 3:
      a = (Base.box)(Base.Int,(Base.add_int)(a::Int64,x::Int64)) # In[18], line 4:
      return a::Int64
  end::Int64


In [22]:
@code_warntype g(3.5)

Variables:
  x::Float64
  a::ANY

Body:
  begin  # In[18], line 2:
      a = 1 # In[18], line 3:
      a = (Base.box)(Base.Float64,(Base.add_float)((Base.box)(Float64,(Base.sitofp)(Float64,a::Int64)),x::Float64)) # In[18], line 4:
      return a::Float64
  end::Float64


In [24]:
@code_native g(3.5)

	.section	__TEXT,__text,regular,pure_instructions
Filename: In[18]
Source line: 2
	pushq	%rbp
	movq	%rsp, %rbp
	pushq	%r14
	pushq	%rbx
	subq	$32, %rsp
	movsd	%xmm0, -48(%rbp)
Source line: 2
	movq	$2, -40(%rbp)
	movabsq	$jl_pgcstack, %r14
	movq	(%r14), %rax
	movq	%rax, -32(%rbp)
	leaq	-40(%rbp), %rax
	movq	%rax, (%r14)
	movabsq	$4389429376, %rax       ## imm = 0x105A16080
Source line: 2
	movq	%rax, -24(%rbp)
Source line: 3
	movq	(%rax), %rbx
	movabsq	$jl_gc_alloc_1w, %rax
	callq	*%rax
	movabsq	$4389698288, %rcx       ## imm = 0x105A57AF0
	movq	%rcx, -8(%rax)
	cvtsi2sdq	%rbx, %xmm0
	addsd	-48(%rbp), %xmm0
	movsd	%xmm0, (%rax)
	movq	%rax, -24(%rbp)
Source line: 4
	movsd	(%rax), %xmm0
	movq	-32(%rbp), %rax
	movq	%rax, (%r14)
	addq	$32, %rsp
	popq	%rbx
	popq	%r14
	popq	%rbp
	ret


In [23]:
@code_native g(3)

	.section	__TEXT,__text,regular,pure_instructions
Filename: In[18]
Source line: 3
	pushq	%rbp
	movq	%rsp, %rbp
Source line: 3
	leaq	1(%rdi), %rax
Source line: 4
	popq	%rbp
	ret


The code is efficient **only** when the function is **type-stable**, i.e. when no variable changes type during the function. In the future, such simple cases should be able to be analysed by more complex compiler optimizations.

## Arrays

Arrays are another fundamental building block of Julia, and there is much sophisticated array functionality.

The simplest way to create an array of a given type and size is with `zeros`, for example a vector:

In [25]:
v = zeros(Int, 3)  # element type; size 3

3-element Array{Int64,1}:
 0
 0
 0

or a matrix:

In [26]:
M = zeros(3, 3)  # default element type is Float64 

3x3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

We see that `Array` is a type with two **type parameters**, the element type and the **dimension** of the array. Note that the size of the array is **not** one of the type parameters, but it available with

In [27]:
size(M)

(3,3)

This returns an object of type

In [28]:
typeof(size(M))

Tuple{Int64,Int64}

`Vector`s (i.e. 1-dimensional `Array`s) may be extended using `push!`:

In [29]:
push!(v, 1)

4-element Array{Int64,1}:
 0
 0
 0
 1

Higher-dimensional arrays have a fixed size. Instead you can push to a `Vector` of `Vector`s:

In [30]:
w = []

0-element Array{Any,1}

In [31]:
push!(w, "David")
append!(w, [3, 4.5, "hello"])
w

4-element Array{Any,1}:
  "David"
 3       
 4.5     
  "hello"

In [32]:
Vector{Int}

Array{Int64,1}

In [33]:
v = Vector{Int}[]
push!(v, [3, 4])
push!(v, [5, 6])
v

2-element Array{Array{Int64,1},1}:
 [3,4]
 [5,6]

In [34]:
M = hcat(v[1], v[2])

2x2 Array{Int64,2}:
 3  5
 4  6

In [35]:
M = hcat(v...)'

2x2 Array{Int64,2}:
 3  4
 5  6

Note that in Julia v0.4, we can write this directly as

In [36]:
v = Vector{Int}[ [3,4], [5,6] ]

2-element Array{Array{Int64,1},1}:
 [3,4]
 [5,6]

by specifying the type of each element of the array comprehension. In Julia v0.5, this may be written simply as

    v = [ [3,4], [5,6] ]

## Performance: don't program in global scope

Coming from other languages, it is natural to write code that looks like the following example simulation of a simple random walker with position `pos`:

In [37]:
@time begin 
pos = 0
numsteps = 10^4
numwalkers = 10^4

final_square_positions = Int[]

for i in 1:numwalkers
    for j in 1:numsteps
        pos += ifelse(rand() < 0.5, -1, +1)
    end
    push!(final_square_positions, pos^2)
end
   
println("Mean square displacement = ", mean(final_square_positions))
end

Mean square displacement = 2.2787585818e7
 13.220538 seconds (380.32 M allocations: 7.159 GB, 5.46% gc time)


We have wrapped the code in a `begin...end` block, and timed it with the `@time` macro. (Note that there is also the `@elapsed` macro, which returns the time in seconds, `@timev` for verbose output, and `@timed` for returning detailed information.)

Is 20 seconds for this calculation slow? We cannot know that without having a comparison code from a compiled language such as C or Fortran. **However**, we see that there are a huge number of allocations, which such a simple code should never have.

This is an immediate warning sign that there Julia is unable to correctly infer the type of some object. In this case, it is because we are working in global scope, which is potentially infinite in size. (Nonetheless, it is a future goal of Julia to reduce this effect.)

The solution is extremely simple: just wrap the code in a function. While we are at it, we should take the opportunity to make the constants into parameters of the function. We can also refactor to separate out a single walker into a separate function:

In [49]:
rand(Bool)

false

In [51]:
function random_walker(numsteps)
    pos = 0
        
    for j in 1:numsteps
        pos += ifelse(rand() < 0.5, -1, +1)
    end
    
    return pos
end


function mean_square_disp(numwalkers, numsteps)
    
    final_square_positions = Int[]

    for i in 1:numwalkers
        final_pos = random_walker(numsteps)
        push!(final_square_positions, final_pos^2)
    end

    return mean(final_square_positions)
end


mean_square_disp (generic function with 1 method)

**Before** we do any timing, we first must ensure that the functions are compiled, by running them once with small values of the parameters:

In [56]:
@code_warntype mean_square_disp(1, 1)

Variables:
  numwalkers::Int64
  numsteps::Int64
  final_square_positions::Array{Int64,1}
  #s52::Int64
  i::Int64
  final_pos::Int64

Body:
  begin  # In[51], line 14:
      final_square_positions = (Main.getindex)(Main.Int)::Array{Int64,1} # In[51], line 16:
      GenSym(0) = $(Expr(:new, UnitRange{Int64}, 1, :(((top(getfield))(Base.Intrinsics,:select_value)::I)((Base.sle_int)(1,numwalkers::Int64)::Bool,numwalkers::Int64,(Base.box)(Int64,(Base.sub_int)(1,1)))::Int64)))
      #s52 = (top(getfield))(GenSym(0),:start)::Int64
      unless (Base.box)(Base.Bool,(Base.not_int)(#s52::Int64 === (Base.box)(Base.Int,(Base.add_int)((top(getfield))(GenSym(0),:stop)::Int64,1))::Bool)) goto 1
      2: 
      GenSym(6) = #s52::Int64
      GenSym(7) = (Base.box)(Base.Int,(Base.add_int)(#s52::Int64,1))
      i = GenSym(6)
      #s52 = GenSym(7) # In[51], line 17:
      final_pos = (Main.random_walker)(numsteps::Int64)::Int64 # In[51], line 18:
      GenSym(2) = (Base.box)(UInt64,(Base.check_top_bit)(1

Now we can immediately do the "production run":

In [55]:
@time mean_square_disp(10^4, 10^4)

  0.289351 seconds (77 allocations: 260.172 KB)


9821.33

This is almost a 50-times speedup, and should be competitive with an implementation in C or Fortran.

## Global variables

Global variables should generally be avoided, but sometimes they are a necessary evil. In this case, they should **always** be declared `const`, in which case the compiler can infer their type and create fast code.

We can obtain a typed but mutable variable in one of two ways: by placing it inside an array, or by placing it inside an object of a user-defined type. In both cases, either the array or the object must be `const` for speed.

In [57]:
const my_number = 3.14159

3.14159

In [58]:
my_number = 10

LoadError: LoadError: invalid redefinition of constant my_number
while loading In[58], in expression starting on line 1

In [59]:
const state = [1]

1-element Array{Int64,1}:
 1

In [60]:
state = 10

LoadError: LoadError: invalid redefinition of constant state
while loading In[60], in expression starting on line 1

In [61]:
state[1] = 10

10

In [62]:
state

1-element Array{Int64,1}:
 10

In [63]:
type MyType
    x::Int
end

In [64]:
my_global = MyType(3)

MyType(3)

In [65]:
my_global.x = 10

10

In [66]:
my_global

MyType(10)